"""
Combines CIGAM Excel export with Odoo sales items CSV into a single dataset.

CIGAM data is filtered to pre-2026 only (Odoo covers 2026 via NF-e extraction).

Field mapping (CIGAM → output):
  item_id        ← Material Cód
  documento_id   ← (empty)
  numero         ← NF             (integer invoice number, stored as string)
  vendedor       ← Representante  (fuzzy-matched to Odoo vendedor names)
  produto_id     ← Material Cód
  produto_nome   ← Material
  ncm            ← Grupo          (product category, not a fiscal NCM code)
  quantidade     ← Quantidade
  vr_unitario    ← Valor Total Item / Quantidade  (zero-safe division)
  vr_nf          ← Valor Total Item
  familia        ← Grupo          (same as ncm for CIGAM; from sped.produto for Odoo)

Odoo source file: outputs/csv/sales_items_odoo_2026.csv
  (generated by src/etl/extract_odoo_2026.py — NF-e level, already contains
   ano, mes, tipo, vendedor, operacao, familia, empresa_id columns)

Vendedor matching (three-pass):
  1. Existing vendedor_mapping.csv (exact/partial pre-resolved matches)
  2. rapidfuzz against unique Odoo vendedor names (score >= 85 → fuzzy)
  3. Fallback: keep original Representante name, mark as no_match
"""

import os
from pathlib import Path

import pandas as pd
from rapidfuzz import process, fuzz

PROJECT_ROOT = Path(__file__).parent.parent.parent

# Normalises CIGAM flat uppercase grupo → proper case matching Odoo parent group
CIGAM_GRUPO_MAP = {
    'SEMENTES':              'Sementes',
    'QUIMICOS':              'Químicos',
    'MAQUINAS':              'Máquinas',
    'PECAS E ACESSORIOS':    'Peças e Acessórios',
    'NUTRICAO':              'Nutrição',
    'SERVICOS':              'Serviços',
    'FERRAGENS E ACESSORIOS':'Ferragens e Acessórios',
    'VETERINARIA':           'Veterinária',
    'IMOBILIZADO':           'Imobilizado',
}

# Normalises CIGAM tipo values to match Odoo convention
CIGAM_TIPO_MAP = {
    'VENDA':                  'venda',
    'VENDA ENTREGA FUTURA':   'venda',
    'DEVOLUCAO':              'devolucao',
    'SERVICO OFICINA':        'os',
    'SERVICO VENDA DIRETA':   'os',
}

# Maps CIGAM UN Cód → (empresa_id, empresa name) matching Odoo res.company
CIGAM_UN_MAP = {
    '001': (1, 'AgroMáquinas Santa Inês'),
    '002': (2, 'AgroMáquinas Bacabal'),
}

EXCEL_PATH   = PROJECT_ROOT / 'BI Cigam - Gestão de Resultado (RICHARD).xlsx'
ODOO_CSV     = PROJECT_ROOT / 'outputs' / 'csv' / 'sales_items_odoo_2026.csv'
MAPPING_CSV  = PROJECT_ROOT / 'outputs' / 'csv' / 'vendedor_mapping.csv'
OUTPUT_CSV   = PROJECT_ROOT / 'outputs' / 'csv' / 'combined_cigam_odoo.csv'
SHEET_NAME   = 0  # first sheet; name uses NFD encoding so index is safer
FUZZY_THRESHOLD = 85


# ── Familia helpers ───────────────────────────────────────────────────────────

def _familia_to_grupo(s: pd.Series) -> pd.Series:
    """
    Normalise familia values to a common top-level group.
      Odoo  : 'Pastagens » Sementes'      → 'Sementes'
      CIGAM : 'SEMENTES'                  → 'Sementes'
    """
    def _convert(val):
        v = str(val)
        if ' » ' in v:
            return v.split(' » ')[-1]
        return CIGAM_GRUPO_MAP.get(v.strip().upper(), v)
    return s.map(_convert)


# ── Vendedor matching ─────────────────────────────────────────────────────────

def load_vendedor_mapping(path: Path) -> tuple:
    """Return (match_map, skip_set).
    match_map: CIGAM rep (upper) → Odoo name for exact/partial.
    skip_set: CIGAM rep (upper) known no_match — skip fuzzy matching."""
    df = pd.read_csv(path, dtype=str).fillna('')
    match_map = {}
    skip_set = set()
    for _, row in df.iterrows():
        cigam_name = row['cigam_representante'].strip().upper()
        odoo_name  = row['odoo_vendedor_id'].strip()
        match_type = row['match_type'].strip()
        if match_type in ('exact', 'partial') and odoo_name:
            match_map[cigam_name] = odoo_name
        elif match_type == 'no_match':
            skip_set.add(cigam_name)
    return match_map, skip_set


def match_vendedor(name: str, pre_map: dict, odoo_names: list,
                   odoo_names_lower: list = None, skip_set: set = None) -> tuple:
    """
    Returns (matched_name, match_type, score).
    Pass 1: pre-resolved mapping CSV.
    Pass 2: skip if explicitly marked no_match in CSV.
    Pass 3: rapidfuzz against Odoo vendedor list (case-insensitive).
    Pass 4: keep original, no_match.
    """
    key = name.strip().upper()

    if key in pre_map:
        return pre_map[key], 'exact', 100

    if skip_set and key in skip_set:
        return name, 'no_match', 0

    # rapidfuzz.WRatio is case-sensitive — normalize to lowercase for comparison
    name_lower = name.strip().lower()
    if odoo_names_lower is None:
        odoo_names_lower = [n.lower() for n in odoo_names]

    result = process.extractOne(name_lower, odoo_names_lower, scorer=fuzz.WRatio)
    if result and result[1] >= FUZZY_THRESHOLD:
        # Map back to original-case Odoo name via index
        idx = odoo_names_lower.index(result[0])
        return odoo_names[idx], 'fuzzy', round(result[1])

    return name, 'no_match', round(result[1]) if result else 0


# ── Odoo builder ──────────────────────────────────────────────────────────────

def build_odoo_df(items_path: Path) -> pd.DataFrame:
    """
    Build Odoo rows from pre-extracted items CSV.
    The CSV is produced by extract_odoo_2026.py (NF-e-level approach) and
    already contains: ano, mes, tipo, operacao, vendedor, familia, empresa_id, etc.
    """
    items = pd.read_csv(items_path, dtype={'produto_id': str, 'item_id': str,
                                           'documento_id': str, 'pedido_id': str,
                                           'produto_codigo': str})

    return pd.DataFrame({
        'source':               'odoo',
        'ano':                  pd.to_numeric(items.get('ano'), errors='coerce').astype('Int64'),
        'mes':                  pd.to_numeric(items.get('mes'), errors='coerce'),
        'tipo':                 items.get('tipo', '').fillna(''),
        'operacao':             items.get('operacao', '').fillna(''),
        'item_id':              items['item_id'],
        'documento_id':         items.get('documento_id', ''),
        'numero':               items.get('numero', ''),
        'vendedor_raw':         items['vendedor'],
        'vendedor':             items['vendedor'],
        'vendedor_match_type':  'odoo',
        'vendedor_match_score': 100,
        'produto_id':           items['produto_id'],
        'produto_codigo':       items.get('produto_codigo', '').fillna(''),
        'produto_nome':         items.get('produto_nome', ''),
        'ncm':                  items.get('ncm', ''),
        'familia':              items.get('familia', 'OUTROS').fillna('OUTROS'),
        'familia_grupo':        _familia_to_grupo(items.get('familia', pd.Series(['OUTROS'] * len(items))).fillna('OUTROS')),
        'empresa_id':           items.get('empresa_id'),
        'empresa':              items.get('empresa', '').fillna(''),
        'quantidade':           pd.to_numeric(items['quantidade'], errors='coerce').fillna(0),
        'vr_unitario':          pd.to_numeric(items['vr_unitario'], errors='coerce').fillna(0),
        'vr_nf':                pd.to_numeric(items['vr_nf'], errors='coerce').fillna(0),
        'tipo_norm':            items.get('tipo', '').fillna(''),
        'cliente':              items.get('cliente', '').fillna(''),
    })


# ── CIGAM builder ─────────────────────────────────────────────────────────────

def load_cigam_raw(excel_path: Path) -> pd.DataFrame:
    print('Loading CIGAM Excel... (this may take a moment)')
    raw = pd.read_excel(
        excel_path,
        sheet_name=SHEET_NAME,
        dtype={'Material Cód': str, 'NF': str, 'UN Cód': str},
        parse_dates=['Data'],
    )
    print(f'  Loaded {len(raw):,} CIGAM rows')
    return raw


def build_cigam_df(raw: pd.DataFrame, pre_map: dict, odoo_names: list,
                   skip_set: set = None) -> pd.DataFrame:
    qtd = pd.to_numeric(raw['Quantidade'], errors='coerce').fillna(0)
    vti = pd.to_numeric(raw['Valor Total Item'], errors='coerce').fillna(0)
    vr_unitario = (vti / qtd.replace(0, float('nan'))).fillna(0)

    unique_reps = raw['Representante'].dropna().unique().tolist()
    print(f'  Matching {len(unique_reps)} unique CIGAM representatives...')
    odoo_names_lower = [n.lower() for n in odoo_names]
    rep_map = {}
    for rep in unique_reps:
        rep_map[rep] = match_vendedor(str(rep), pre_map, odoo_names, odoo_names_lower, skip_set)

    matched_vendor = raw['Representante'].map(lambda x: rep_map.get(str(x), (str(x), 'no_match', 0))[0])
    match_type     = raw['Representante'].map(lambda x: rep_map.get(str(x), (str(x), 'no_match', 0))[1])
    match_score    = raw['Representante'].map(lambda x: rep_map.get(str(x), (str(x), 'no_match', 0))[2])

    dates = pd.to_datetime(raw['Data'], errors='coerce')
    grupo = raw['Grupo'].fillna('OUTROS').astype(str)

    cigam_tipo = raw['Operação Resultado'].astype(str)
    tipo_norm = cigam_tipo.str.strip().str.upper().map(CIGAM_TIPO_MAP).fillna('outro')

    # Override: VENDA rows with 5117*-REMESSA tipo de operação → remessa
    tipo_op_col = [c for c in raw.columns if c.startswith('Tipo de Oper')][0]
    is_remessa = (
        (cigam_tipo.str.strip().str.upper() == 'VENDA')
        & raw[tipo_op_col].astype(str).str.contains('5117', na=False)
    )
    tipo_norm = tipo_norm.where(~is_remessa, 'remessa')

    return pd.DataFrame({
        'source':               'cigam',
        'ano':                  dates.dt.year.astype('Int64'),
        'mes':                  dates.dt.month,
        'tipo':                 cigam_tipo,
        'operacao':             cigam_tipo,
        'item_id':              raw['Material Cód'],
        'documento_id':         '',
        'numero':               raw['NF'].astype(str),
        'vendedor_raw':         raw['Representante'].astype(str),
        'vendedor':             matched_vendor,
        'vendedor_match_type':  match_type,
        'vendedor_match_score': match_score,
        'produto_id':           raw['Material Cód'],
        'produto_codigo':       raw['Material Cód'],
        'produto_nome':         raw['Material'].astype(str),
        'ncm':                  grupo,
        'familia':              grupo,
        'familia_grupo':        _familia_to_grupo(grupo),
        'empresa_id':           raw['UN Cód'].astype(str).map(lambda x: CIGAM_UN_MAP.get(x.strip(), (None, ''))[0]),
        'empresa':              raw['UN Cód'].astype(str).map(lambda x: CIGAM_UN_MAP.get(x.strip(), (None, ''))[1]),
        'quantidade':           qtd,
        'vr_unitario':          vr_unitario,
        'vr_nf':                vti,
        'tipo_norm':            tipo_norm,
        'cliente':              raw['Empresa'].astype(str).fillna(''),
    })


# ── Reports ───────────────────────────────────────────────────────────────────

def print_match_report(cigam_df: pd.DataFrame) -> None:
    print('\n── Vendedor Match Report ──────────────────────────────')
    summary = (
        cigam_df.groupby(['vendedor_raw', 'vendedor_match_type', 'vendedor_match_score', 'vendedor'])
        .size()
        .reset_index(name='rows')
        .sort_values(['vendedor_match_type', 'vendedor_match_score'], ascending=[True, False])
    )
    for mtype in ['exact', 'fuzzy', 'no_match']:
        group = summary[summary['vendedor_match_type'] == mtype]
        if group.empty:
            continue
        print(f'\n[{mtype.upper()}] ({len(group)} unique reps)')
        for _, row in group.iterrows():
            arrow = f'→ {row["vendedor"]}' if row['vendedor'] != row['vendedor_raw'] else ''
            print(f'  {row["vendedor_raw"][:45]:<45} score={row["vendedor_match_score"]:>3}  {arrow}  ({row["rows"]} rows)')
    print()


def print_familia_report(combined: pd.DataFrame) -> None:
    print('\n── Familia Report ─────────────────────────────────────')
    summary = (
        combined.groupby(['source', 'familia'])['vr_nf']
        .agg(vr_nf_total='sum', rows='count')
        .reset_index()
        .sort_values(['source', 'vr_nf_total'], ascending=[True, False])
    )
    for src in ['odoo', 'cigam']:
        grp = summary[summary['source'] == src]
        print(f'\n[{src.upper()}]')
        for _, row in grp.iterrows():
            print(f'  {row["familia"]:<35}  R$ {row["vr_nf_total"]:>14,.0f}  ({row["rows"]:,} rows)')
    print()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    raw_cigam = load_cigam_raw(EXCEL_PATH)

    print('Loading Odoo CSV...')
    odoo_df = build_odoo_df(ODOO_CSV)
    print(f'  {len(odoo_df):,} Odoo rows loaded')

    print('Loading vendedor mapping...')
    pre_map, skip_set = load_vendedor_mapping(MAPPING_CSV)
    odoo_names = odoo_df['vendedor'].dropna().unique().tolist()
    print(f'  {len(pre_map)} pre-resolved mappings, {len(skip_set)} skip entries, {len(odoo_names)} unique Odoo vendedores')

    cigam_df = build_cigam_df(raw_cigam, pre_map, odoo_names, skip_set)

    # Filter CIGAM to pre-2026 only (Odoo covers 2026)
    pre_2026 = cigam_df['ano'] < 2026
    n_dropped = (~pre_2026).sum()
    cigam_df = cigam_df[pre_2026].reset_index(drop=True)
    print(f'  Filtered CIGAM to pre-2026: kept {len(cigam_df):,}, dropped {n_dropped:,} rows')

    print_match_report(cigam_df)

    combined = pd.concat([odoo_df, cigam_df], ignore_index=True)

    print_familia_report(combined)

    os.makedirs(OUTPUT_CSV.parent, exist_ok=True)
    combined.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')

    print(f'Output : {OUTPUT_CSV}')
    print(f'Total rows : {len(combined):,}')
    print(f'  odoo     : {len(odoo_df):,}')
    print(f'  cigam    : {len(cigam_df):,}')


if __name__ == '__main__':
    main()
